lotos/base/urls.py
from django.conf.urls import url
from .views import (
    PageIndex, PageAbout
)

urlpatterns = [
    url(r'^$', PageIndex.as_view(), name='index'),
    url(r'^about/$', PageAbout.as_view(), name='about'),
]

lotos/lotos/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('base.urls', namespace='base')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^goods/', include('product.urls', namespace='goods')),
    url(r'^wishlist/', include('wishlist.urls', namespace='wishlist')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lotos/product/urls.py
from django.conf.urls import url
from .views import (
    ProductsListView, DiscountsListView
)

urlpatterns = [
    url(r'^discounts/$', DiscountsListView.as_view(), name='discounts'),
    url(r'^$', ProductsListView.as_view(), name='list'),
]

lotos/wishlist/urls.py
from django.conf.urls import url
from .views import (
    WishlistIndexView, WishlistAddView, WishlistDeleteView
)

urlpatterns = [
    url(r'^$', WishlistIndexView.as_view(), name='index'),
    url(r'^add/$', WishlistAddView.as_view(), name='add'),
    url(r'^delete/$', WishlistDeleteView.as_view(), name='delete'),
]

lotos/product/models.py
from django.conf import settings
from django.db import models
import os, uuid

def get_product_image(instance, filename):
    ext = filename.split('.')[-1]
    filename = "{0}.{1}".format(uuid.uuid4(), ext)
    return os.path.join('goods', filename)

class Product(models.Model):
    UNIT_CHOICES = (
        ('кг', 'Килограммы'),
        ('г', 'Граммы'),
        ('л', 'Литры')
    )
    CATEGORY_CHOICES = (
        ('овощи', 'Овощи'),
        ('фрукты', 'Фрукты'),
        ('рыба', 'Рыба'),
        ('мясо', 'Мясо'),
        ('напитки', 'Напитки'),
        ('алкоголь', 'Алкоголь'),
    )
    name = models.CharField(
        db_index=True,
        max_length=64,
        unique=True,
        verbose_name='Название товара'
    )
    quantity = models.PositiveSmallIntegerField(
        default=1, verbose_name='Количество')
    unit = models.CharField(
        choices=UNIT_CHOICES,
        default='кг',
        max_length=16,
        verbose_name='Единица измерения'
    )
    category = models.CharField(
        choices=CATEGORY_CHOICES,
        default='мясо',
        max_length=64,
        verbose_name='Категория товара'
    )
    price = models.PositiveIntegerField(
        default=0, verbose_name='Стартовая цена')
    percentage = models.PositiveSmallIntegerField(
        default=100, verbose_name='Скидка/Наценка')
    img = models.ImageField(
        upload_to=get_product_image, verbose_name='Изображение товара', null=True)

    transaction = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='WishlistTransaction'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

class WishlistTransaction(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )
    date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата транзакции'
    )

lotos/product/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        exclude = ('pk',)

lotos/product/views.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin
)
from django.shortcuts import render, redirect, reverse
from django.views.generic.base import (
    TemplateView, View
)
from .models import Product

class ProductsListView(TemplateView):
    template_name = 'product.html'

    def get_context_data(self, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        context['goods'] = Product.objects.all()

        return context

class DiscountsListView(TemplateView):
    template_name = 'discount.html'

    def get_context_data(self, **kwargs):
        context = super(DiscountsListView, self).get_context_data(**kwargs)
        context['discounts'] = Product.objects.filter(
            percentage__lt=100
        )

        return context

lotos/product/templates/discount.html
{% extends 'logo.html' %}

{% block content %}

<div class="container">
  <div class="row">
    {% if discounts|length %}
      {% for discount in discounts %}
      <div class="col-md-4" style="margin-top: 20px;">
        <a href="#" class="thumbnail">
          <img src="/{{ discount.img.url }}" alt="{{ discount.name }}">
          <div class="alert alert-info" style="margin-bottom: 0px; text-align: center;">
            {{ discount.name }}
            <br/>
            Скидка {{ discount.percentage|add:"-100" }}%
          </div>
        </a>
      </div>
      {% endfor %}
    {% else %}
    <small>Скидки отсутствуют</small>
    {% endif %}
  </div>
</div>

{% endblock %}

lotos/product/templates/drop_product.html
{% block drop_product %}

<form id="drop_transaction-form" action="{% url 'wishlist:delete' %}" method="POST" style="display: none;">
  {% csrf_token %}
  <input id="drop_transaction-input" name="drop_transaction" type="text">
</form>

<script>
  function drop_product(self, pk) {
    $('#drop_transaction-input').val(pk);
    $('#drop_transaction-modal .modal-body').html(
      "Вы собираетесь удалить товар <strong>"
      + $(self).attr('data-name') + "</strong>"
      + "Вы уверены в этом?"
    );
    $('#drop_transaction-modal').modal('show');
  };
</script>

<div class="modal fade" id="drop_transaction-modal" tabindex="-1" role="dialog" aria-labelledby="drop_transaction-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="drop_transaction-label">Удаление товара из списка желаемого</h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" onclick="$('#drop_transaction-form').submit()">Удалить товар</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

lotos/product/templates/product.html
{% extends 'logo.html' %}

{% block content %}
{% include 'pick_product.html' %}
<div class="container">
  <div class="row">
    {% if goods|length %}
    {% for product in goods %}
    <div class="col-md-4" style="margin-top: 20px;">
      <a
        href="#"
        onclick="pick_product(this, {{ product.pk }})"
        data-name="{{ product.name }}"
        data-quantity="{{ product.quantity }}"
        data-unit="{{ product.unit }}"
        data-price="{{ product.price }}"
        data-percentage="{{ product.percentage }}"
        class="thumbnail">
        <img src="/{{ product.img.url }}" alt="{{ product.name }}">
        <div class="alert alert-info" style="margin-bottom: 0px; text-align: center;">
          {{ product.name }}

        </div>
      </a>
    </div>
    {% endfor %}
    {% else %}
    <h4>Товаров нет.</h4>
    {% endif %}
  </div>
</div>

{% endblock %}