lotos/account/urls.py
from django.conf.urls import url
from .views import (
    AccountSigninView, AccountLogoutView, AccountSignupView,
    AccountDetailView
)

urlpatterns = [
    url(r'^signin/$', AccountSigninView.as_view(), name='signin'),
    url(r'^logout/$', AccountLogoutView.as_view(), name='logout'),
    url(r'^signup/$', AccountSignupView.as_view(), name='signup'),
    url(
        r'^(?P<email>[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)$',
        AccountDetailView.as_view(), name='detail'
    )
]

lotos/article/urls.py
from django.conf.urls import url
from .views import (
    ArticleArchiveView, ArticleControlView, ArticlePageView
)

urlpatterns = [
    url(r'^$', ArticleArchiveView.as_view(), name='archive'),
    url(r'^control/$', ArticleControlView.as_view(), name='control'),
    url(r'^(?P<pk>\d+)$', ArticlePageView.as_view(), name='page')
]

lotos/base/urls.py
from django.conf.urls import url
from .views import (
    PageIndex, PageAbout
)

urlpatterns = [
    url(r'^$', PageIndex.as_view(), name='index'),
    url(r'^about/$', PageAbout.as_view(), name='about'),
]

lotos/lotos/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('base.urls', namespace='base')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^goods/', include('product.urls', namespace='goods')),
    url(r'^wishlist/', include('wishlist.urls', namespace='wishlist')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lotos/product/urls.py
from django.conf.urls import url
from .views import (
    ProductsListView, DiscountsListView
)

urlpatterns = [
    url(r'^discounts/$', DiscountsListView.as_view(), name='discounts'),
    url(r'^$', ProductsListView.as_view(), name='list'),
]

lotos/article/models.py
from django.conf import settings
from django.db import models

class Article(models.Model):
    caption = models.CharField(db_index=True, max_length=256, verbose_name='Заголовок статьи')
    body = models.TextField(max_length=5000, verbose_name='Тело статьи')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Пользователь'
    )

    def __str__(self):
        return self.caption

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['-date']

lotos/base/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from account.forms import (
    LoginForm, UserCreationForm
)
from article.models import Article
from product.models import Product

class PageIndex(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(PageIndex, self).get_context_data(**kwargs)
        context['form'] = LoginForm
        context['form_reg'] = UserCreationForm
        context['articles'] = Article.objects.all()[:8]
        context['discounts'] = Product.objects.filter(
            percentage__lt=100
        ).order_by('?')[:5]

        return context

class PageAbout(TemplateView):
    template_name = 'about.html'

lotos/base/templates/about.html
{% extends 'logo.html' %}

{% block content %}
<div class="container">
  <div class="row" style="text-align: center;">
    <h3>О предприятии</h3>
  </div>
  <hr/>
  <div class="row" style="margin-bottom: 20px;">
    <div style="text-align: justify; text-indent: 35.4pt;">
      Холдинг &laquo;Лотос&raquo; одно из крупнейших, стабильных и постоянно
      развивающихся&nbsp;предприятий Республики Карелия. В 1989 году в городе
      Петрозаводске было создано первое&nbsp;небольшое коммерческое предприятие
      &laquo;Лотос&raquo;. С тех пор,&nbsp;за&nbsp;более четверти века, из
      небольшой фирмы, вырос холдинг &laquo;Лотос&raquo;, в состав которого входят:
      гипермаркет &laquo;Сигма&raquo;,&nbsp;первый в Петрозаводске супермаркет
      премиум-класса &laquo;Лотос Гурман&raquo;,&nbsp;&nbsp;5 супермаркетов, база
      отдыха &laquo;Радуга&raquo;,&nbsp; ДК &laquo;Машиностроитель&raquo;,
      ресторан &laquo;Пинта паб&raquo;, кафе &laquo;Сигма сити&raquo;&nbsp;и
      гостиница &laquo;Северная&raquo;.</div>
    <div style="text-align: justify; text-indent: 35.4pt;">Компания непрерывно
      развивается, наращивает потенциал, совершенствует бизнес-процессы, повышая
      эффективность, старается быть пионером, в тех областях, в направлении которых
      ведет развитие. Новаторство является одним из главных &nbsp;конкурентных
      преимуществ в управлении холдингом &laquo;Лотос&raquo;. Достаточно вспомнить,
      что в 90-годы фирма &laquo;Лотос&raquo; одна из первых в городе открыла
      современные и комфортные магазины с круглосуточным обслуживанием, в 1996
      году на улице Анохина 37 появился первый в Карелии супермаркет
      самообслуживания. В декабре 2004 года открылся первый в Республике
      современный гипермаркет розничной торговли &laquo;Сигма&raquo;, а в декабре
      2010 единственный во всем регионе супермаркет премиум-класса &laquo;Лотос
      Гурман&raquo;</div>
    <div style="text-align: justify; text-indent: 35.4pt;">С 2008 года, когда под
      маркой &laquo;Пинта Паб&raquo;, открыл двери пивной бар и Березовой аллее
      25а, активно развивается направление по организации общественного питания.
      Сегодня в холдинг &laquo;Лотос&raquo;, помимо &laquo;Пинта Паба&raquo; входят
      два кафе &ndash; &laquo;Сигма сити&raquo; и &laquo;Блинная&raquo;.</div>
    <div style="text-align: justify; text-indent: 35.4pt;">&nbsp;Благодаря быстрому
      реагированию на изменение рынка, следование тенденциям рынка, современным
      реалиям бизнеса, а нередко и являясь катализатором бизнес-процессов, холдинг
      &laquo;Лотос&raquo; много лет остается признанным лидером в сфере услуг на
      рынке Карелии и одним из ведущих и престижнейших работодателей города
      Петрозаводска и Республики. Компания непрерывно развивается, наращивает
      потенциал, повышает эффективность сети, качество представленных товаров
      и услуг, уровень обслуживания покупателей, развивает новые направления
      бизнеса.</div>
    <div style="text-align: justify; text-indent: 35.4pt;">Сегодня, следуя
      приоритетному направлению &ndash; развития туристского потенциала
      Республики Карелия, холдинг &laquo;Лотос&raquo; стал собственником
      одного из ведущих туристских предприятий Петрозаводска &ndash; гостиницы
      &laquo;Северная&raquo;, по мимо этого, в активе холдинга находится турбаза
      &laquo;Радуга&raquo;. Гостям и жителям Карелии, холдинг &laquo;Лотос&raquo;
      готов предложить, не только комфортное размещение, но и активный отдых,
      благодаря новому направлению бизнеса &ndash; фрахт яхт и катеров.</div>
    <div style="text-align: justify; text-indent: 35.4pt;">Одним из приоритетных
      направлений развития, руководство холдинга &laquo;Лотос&raquo; считает
      инвестиционную и девелоперскую деятельность, курс на освоение которых,
      единогласно принят топ-менеджерами.</div>
    <div style="text-align: justify; text-indent: 35.4pt;">&nbsp;Холдинг
      &laquo;Лотос&raquo; это стабильный работодатель, ответственный член
      современного делового общества и надежный партнер, поддерживающий высокий
      уровень социальной ответственности. Холдинг &laquo;Лотос&raquo; уделяет
      большое внимание благотворительной деятельности, как очень важному
      направлению в решении социальных задач. Холдинг &laquo;Лотос&raquo;
      растет, разрабатывает планы перспективного развития. Расширение ассортимента,
      высокое качество продукции собственного производства, культуры обслуживания -
      первостепенные задачи холдинга.</div>
  </div>
  <hr/>
</div>

{% endblock %}

lotos/base/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load static %}
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/main.css" %}">
  <title>{{ page_title }}</title>
</head>
<body>
  {% include 'header.html' %}
  {% block logo %}
  {% endblock %}
  {% block sidenavbar %}
  {% endblock %}
  <script src="{% static "js/jquery-3.2.1.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  {% block content %}
  {% endblock %}
  <footer class="lotos-page__footer">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          &#169; 2005-2017 Холдинг &#171;Лотос&#187;
        </div>
        <div class="col-md-4">
          <ul>
            <li><a href="{% url 'article:archive' %}">Архив новостей</a></li>
            <li><a href="{% url 'goods:list' %}">Ассортимент</a></li>
            <li><a href="{% url 'goods:discounts' %}">Скидки</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <ul>
            <li>
              <a href="http://thlotos.ru/objects/retail/sigma/">
                Гипермаркет "Сигма"
              </a>
            </li>
            <li>
              <a href="http://thlotos.ru/objects/retail/gurman/">
                Лотос Гурман
              </a>
            </li>
            <li>
              <a href="http://thlotos.ru/objects/retail/center/">
                Торговый комплекс "Лотос Центр"
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
</body>
</html>

lotos/base/templates/header.html
{% block header %}
{% load static %}
<nav class="navbar navbar-inverse lotos-page-nav">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <img src="{% static "imgs/lotos-logo.png" %}" alt="">
      </a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'article:archive' %}">Новости</a></li>
      <li><a href="{% url 'goods:list' %}">Ассортимент</a></li>
      <li><a href="{% url 'goods:discounts' %}">Скидки</a></li>
      <li><a href="{% url 'base:about' %}">О нас</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if not user.is_authenticated %}
      <li>
        <a href="#login" data-toggle="modal" data-target="#login">
          <span class="glyphicon glyphicon-log-in"></span> Войти
        </a>
      </li>
      <li>
        <a href="#signup" data-toggle="modal" data-target="#signup">
          <span class="glyphicon glyphicon-user"></span> Регистрация
        </a>
      </li>
      {% else %}
      <li style="padding-top: 8px;">
        <button
          class="btn btn-default dropdown-toggle"
          type="button" id="dropdownAccount"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="true">
          Вы зашли как {{ user.email }}
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownAccount">
          <li><a href="{% url 'account:detail' email=user.email %}">Информация</a></li>
          <li><a href="{{ user.is_superuser|yesno:"/admin, /dashboard" }}">Панель управления</a></li>
          {% if user.is_staff %}
          <li><a href="{% url 'dashboard:index' %}">Администрирование</a></li>
          {% endif %}
          <li role="separator" class="divider"></li>
          <li><a href="{% url 'account:logout' %}">Выйти</a></li>
        </ul>
      </li>
      {% endif %}
      <li>
        <a href="{% url 'wishlist:index' %}" class="lotos-page-nav__wish-list">
          <span class="glyphicon glyphicon-heart"></span>
          Корзина
          <span class="badge">{{ user.product_set.count }}</span>
        </a>
      </li>
    </ul>
  </div>
</nav>

<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="loginLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="loginLabel">Вход</h4>
      </div>
      <div class="modal-body">
        <div class="alert alert-info" role="alert">
          Удостоверьтесь, что ваш аккаунт <strong>существует</strong>, иначе авторизация не будет пройдена.
          Для регистрации нового аккаунта необходимо выбрать пункт в меню <strong>Регистрация</strong>.
        </div>
        <form id="login-form" action="{% url 'account:signin' %}" method="POST">
          {% csrf_token %}
          <div class="input-group">
            <span class="input-group-addon" id="email-login">
              <i class="glyphicon glyphicon-envelope"></i>
              Почта
            </span>
            {{ form.email }}
          </div>
          <div class="input-group" style="margin-top: 15px;">
            <span class="input-group-addon" id="password-login">
              <i class="glyphicon glyphicon-lock"></i>
              Пароль
            </span>
            {{ form.password }}
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" onclick="$('#login-form').submit()">Войти</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="signupLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="signupLabel">Регистрация</h4>
      </div>
      <div class="modal-body">
        <div class="alert alert-info" role="alert">
          Для <strong>регистрации</strong> необходимо, чтобы ваш <strong>e-mail</strong> был не занят кем-то другим.
        </div>
        <form id="signup-form" action="{% url 'account:signup' %}" method="POST">
          {% csrf_token %}
          <div class="input-group">
            <span class="input-group-addon" id="email-signup">
              <i class="glyphicon glyphicon-envelope"></i>
              Почта
            </span>
            {{ form_reg.email }}
          </div>
          <div class="input-group" style="margin-top: 15px;">
            <span class="input-group-addon" id="password1-signup">
              <i class="glyphicon glyphicon-lock"></i>
              Пароль
            </span>
            {{ form_reg.password1 }}
          </div>
          <div class="input-group" style="margin-top: 15px;">
            <span class="input-group-addon" id="password2-signup">
              <i class="glyphicon glyphicon-lock"></i>
              Повторите пароль
            </span>
            {{ form_reg.password2 }}
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" onclick="$('#signup-form').submit()">Регистрация</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

lotos/base/templates/index.html
{% extends 'logo.html' %}

{% block content %}

<div class="container">
  <div class="col-md-8">
    <h4>Интересное</h4>
    <div id="lotos-page-carousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#lotos-page-carousel" data-slide-to="0" class="active"></li>
        <li data-target="#lotos-page-carousel" data-slide-to="1"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="http://thlotos.ru/upload/iblock/abd/abdbb121a2f58e15b1ec04b92272bfa3.jpg" alt="">
        </div>
        <div class="item">
          <img src="http://thlotos.ru/upload/iblock/72b/72bd323e0bd64bb221065bb66183626b.jpg" alt="">
        </div>
      </div>
      <a class="left carousel-control" href="#lotos-page-carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Предыдущий</span>
      </a>
      <a class="right carousel-control" href="#lotos-page-carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Следующий</span>
      </a>
    </div>
    <h4>Лента новостей</h4>
    {% if articles|length %}
      {% for item in articles %}
      <div class="row lotos-page__news" style="padding: 5px 15px;">
        <h4>
          <a href="{% url 'article:page' pk=item.pk %}">{{ item.caption }}</a>
        </h4>
        <p class="lotos-page__news-body">
          {% autoescape off %}
            {{ item.body|striptags|truncatechars:128 }}
          {% endautoescape %}
        </p>
        <div class="row">
          <div class="col-md-8">
            <p class="lotos-page__news-date"><span class="glyphicon glyphicon-calendar"></span> {{ item.date|timesince }} назад</p>
          </div>
          <div class="col-md-4">
            <a href="">Подробнее</a>
          </div>
        </div>
      </div>
      <hr/>
      {% endfor %}
    {% else %}
    <smal>Статей нет.</smal>
    {% endif %}
  </div>
  {% include 'pick_product.html' %}
  <div class="col-md-4">
    <h4>Случайные скидки</h4>
    {% if discounts|length %}
      {% for discount in discounts %}
      <a
        href="#"
        onclick="pick_product(this, {{ discount.pk }})"
        class="thumbnail"
        data-name="{{ discount.name }}"
        data-quantity="{{ discount.quantity }}"
        data-unit="{{ discount.unit }}"
        data-price="{{ discount.price }}"
        data-percentage="{{ discount.percentage }}">
        <img src="{{ discount.img.url }}" alt="{{ discount.name }}">
        <div class="alert alert-info" style="margin-bottom: 0px; text-align: center;">
          {{ discount.name }}
          <br/>
          Скидка {{ discount.percentage|add:"-100" }}%
        </div>
      </a>
      {% endfor %}
    {% else %}
      <small>Скидки отсутствуют</small>
    {% endif %}
  </div>
  {% if user.product_set.count >= 2 %}
  <div class="row" style="clear: both;">
    asd
  </div>
  {% endif %}
</div>

{% endblock %}

lotos/base/templates/logo.html
{% extends 'base.html' %}

{% block logo %}

<header id="lotos-page-header"></header>
{% if messages %}
<div class="container lotos-page__messages">
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}

{% endblock %}

lotos/base/templates/sidenavbar.html
{% extends 'base.html' %}

{% block sidenavbar %}

<div class="row-offcanvas row-offcanvas-left">
  <div id="sidebar" class="sidebar-offcanvas">
      <div class="col-md-12">
        <h3>Управление</h3>
        <ul class="nav nav-pills nav-stacked">
          {% load base.tags %}
          <li {% highlight_active 'dashboard:index' %}>
            <a href="{% url 'dashboard:index' %}">
              Общая информация
              <span
                style="font-size:16px;"
                class="pull-right hidden-xs showopacity glyphicon glyphicon-home">
              </span>
            </a>
          </li>
          {% if perms.articles.add_article and perms.articles.change_article and perms.articles.delete_article %}
          <li {% highlight_active 'dashboard:articles' %}>
            <a href="{% url 'dashboard:articles' %}">
              Статьи
              <span
                style="font-size:16px;"
                class="pull-right hidden-xs showopacity glyphicon glyphicon-book">
              </span>
            </a>
          </li>
          {% endif %}
          {% if perms.goods.add_goods and perms.goods.change_goods and perms.goods.delete_goods %}
          <li>
            <a href="#">
              Товары
              <span
                style="font-size:16px;"
                class="pull-right hidden-xs showopacity glyphicon glyphicon-shopping-cart">
              </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
  </div>

{% endblock %}