lotos/base/urls.py
from django.conf.urls import url
from .views import (
    PageIndex, PageAbout
)

urlpatterns = [
    url(r'^$', PageIndex.as_view(), name='index'),
    url(r'^about/$', PageAbout.as_view(), name='about'),
]

lotos/lotos/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('base.urls', namespace='base')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^goods/', include('product.urls', namespace='goods')),
    url(r'^wishlist/', include('wishlist.urls', namespace='wishlist')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lotos/wishlist/urls.py
from django.conf.urls import url
from .views import (
    WishlistIndexView, WishlistAddView, WishlistDeleteView
)

urlpatterns = [
    url(r'^$', WishlistIndexView.as_view(), name='index'),
    url(r'^add/$', WishlistAddView.as_view(), name='add'),
    url(r'^delete/$', WishlistDeleteView.as_view(), name='delete'),
]

lotos/wishlist/models.py
from django.db import models

lotos/wishlist/views.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin
)
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.base import (
    TemplateView, View
)
from product.models import Product, WishlistTransaction

class WishlistIndexView(TemplateView):
    template_name = "wishlist.html"

    def get_context_data(self, **kwargs):
        context = super(WishlistIndexView, self).get_context_data(**kwargs)
        context['goods'] = WishlistTransaction.objects.filter(
            user__email=self.request.user.email
        )

        return context

class WishlistAddView(LoginRequiredMixin, View):
    login_url = '/'

    def post(self, request):
        product_id = request.POST.get('pick_product', None)
        if product_id is None:
            return redirect(reverse('base:index'))
        product = get_object_or_404(Product, pk=product_id)
        m2m = WishlistTransaction(
            user=request.user,
            product=product
        )
        m2m.save()
        return redirect(reverse('wishlist:index'))

class WishlistDeleteView(LoginRequiredMixin, View):
    login_url = '/'

    def post(self, request):
        transaction_id = request.POST.get('drop_transaction', None)
        if transaction_id is None:
            return redirect(reverse('base:index'))
        transaction = get_object_or_404(WishlistTransaction, pk=transaction_id)
        transaction.delete()
        return redirect(reverse('wishlist:index'))

lotos/wishlist/templates/pick_product.html
{% block pick_product %}

<form id="pick-product-form" action="{% url 'wishlist:add' %}" method="POST" style="display: none;">
  {% csrf_token %}
  <input id="pick-product-input" name="pick_product" type="text">
</form>

<script>

  function pick_product(self, pk) {
    $('#pick-product-input').val(pk);
    // change modal inner
    var price = parseInt($(self).attr('data-price'));
    var percentage = parseInt($(self).attr('data-percentage')) / 100;
    var result_price = Math.ceil(price * percentage);
    $('#pick-product-modal .modal-body').html(
      "Вы собираетесь добавить в список желаемого товар <strong>"
      + $(self).attr('data-name') + "</strong>"
      + " за " + $(self).attr('data-quantity')
      + " " + $(self).attr('data-unit') + ". По итоговой цене: "
      + "<mark>" + result_price + " рублей.</mark>"
    );
    $('#pick-product-modal').modal('show');
  };
</script>

<div class="modal fade" id="pick-product-modal" tabindex="-1" role="dialog" aria-labelledby="pick-product-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="pick-product-label">Добавление товара в список желаемого</h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" onclick="$('#pick-product-form').submit()">Добавить товар</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

lotos/wishlist/templates/wishlist.html
{% extends 'logo.html' %}

{% block content %}
{% include 'drop_product.html' %}
<div class="container">
  <div class="row">
    <h3>Товаров в вашей корзине {{ goods.count }}.</h3>
  </div>
  <hr/>
  {% if goods.count %}
  <div class="row">
  {% for prod in goods %}
    <div class="col-md-4">
      <a
        href="#"
        onclick="drop_product(this, {{ prod.pk }})"
        data-name="{{ prod.product.name }}"
        class="thumbnail">
        <img src="/{{ prod.product.img.url }}" alt="{{ prod.product.name }}">
        <div class="alert alert-info" style="margin-bottom: 0px; text-align: center;">
          {{ prod.product.name }}
        </div>
      </a>
    </div>
  {% endfor %}
  </div>
  {% endif %}
  <hr/>
</div>

{% endblock %}